--
-- Script was generated by Devart dbForge Studio 2019 for MySQL, Version 8.2.23.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 30.3.2020. 17:13:32
-- Server version: 5.5.5-10.4.11-MariaDB
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

--
-- Set default database
--
USE paup;

--
-- Drop table `admin_1`
--
DROP TABLE IF EXISTS admin_1;

--
-- Drop table `ugovor`
--
DROP TABLE IF EXISTS ugovor;

--
-- Drop table `auto`
--
DROP TABLE IF EXISTS auto;

--
-- Drop table `korisnici`
--
DROP TABLE IF EXISTS korisnici;

--
-- Set default database
--
USE paup;

--
-- Create table `korisnici`
--
CREATE TABLE korisnici (
  Ime VARCHAR(10) DEFAULT NULL,
  Prezime VARCHAR(25) DEFAULT NULL,
  Mail_Kor VARCHAR(50) NOT NULL,
  Lozinka VARCHAR(20) DEFAULT NULL,
  God_Rod DATE DEFAULT NULL,
  PRIMARY KEY (Mail_Kor)
)
ENGINE = INNODB,
CHARACTER SET cp1250,
COLLATE cp1250_croatian_ci;

--
-- Create table `auto`
--
CREATE TABLE auto (
  IdAuto INT(10) NOT NULL AUTO_INCREMENT,
  Marka VARCHAR(25) DEFAULT NULL,
  Model VARCHAR(255) DEFAULT NULL,
  Obujam INT(10) DEFAULT NULL,
  Snaga INT(10) DEFAULT NULL,
  Kilaza INT(10) DEFAULT NULL,
  Max_Brzina INT(10) DEFAULT NULL,
  Ubrzanje FLOAT(30, 2) DEFAULT NULL,
  Cijena VARCHAR(20) DEFAULT NULL,
  PRIMARY KEY (IdAuto)
)
ENGINE = INNODB,
CHARACTER SET cp1250,
COLLATE cp1250_croatian_ci;

--
-- Create index `Auto_Model` on table `auto`
--
ALTER TABLE auto 
  ADD UNIQUE INDEX Auto_Model(Model);

--
-- Create table `ugovor`
--
CREATE TABLE ugovor (
  IdUgovor INT(10) NOT NULL AUTO_INCREMENT,
  Mail_Ug VARCHAR(50) DEFAULT NULL,
  Model VARCHAR(255) DEFAULT NULL,
  Datum DATE DEFAULT NULL,
  Vrijeme_Od TIME DEFAULT NULL,
  Vrijeme_Do TIME DEFAULT NULL,
  PRIMARY KEY (IdUgovor)
)
ENGINE = INNODB,
CHARACTER SET cp1250,
COLLATE cp1250_croatian_ci;

--
-- Create foreign key
--
ALTER TABLE ugovor 
  ADD CONSTRAINT Auto_Key FOREIGN KEY (Model)
    REFERENCES auto(Model) ON UPDATE CASCADE;

--
-- Create foreign key
--
ALTER TABLE ugovor 
  ADD CONSTRAINT Mail_Key FOREIGN KEY (Mail_Ug)
    REFERENCES korisnici(Mail_Kor) ON UPDATE CASCADE;

--
-- Create table `admin_1`
--
CREATE TABLE admin_1 (
  Ime_Admin VARCHAR(25) NOT NULL,
  Lozinka_Admin VARCHAR(25) DEFAULT NULL,
  PRIMARY KEY (Ime_Admin)
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 16384,
CHARACTER SET cp1250,
COLLATE cp1250_croatian_ci;

-- 
-- Dumping data for table korisnici
--
-- Table paup.korisnici does not contain any data (it is empty)

-- 
-- Dumping data for table auto
--
-- Table paup.auto does not contain any data (it is empty)

-- 
-- Dumping data for table ugovor
--
-- Table paup.ugovor does not contain any data (it is empty)

-- 
-- Dumping data for table admin_1
--
INSERT INTO admin_1 VALUES
('Admin', 'admin');

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;